import type { NextConfig } from "next";
import redirectsData from "./src/data/redirects.json" with { type: "json" };

type RedirectEntry = { source: string; destination: string; permanent: boolean };

const securityHeaders = [
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "X-Frame-Options", value: "SAMEORIGIN" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  images: {
    formats: ["image/avif", "image/webp"],
    qualities: [60, 75],
    deviceSizes: [360, 390, 430, 640, 768, 828, 1024, 1280, 1440, 1920],
    imageSizes: [64, 96, 128, 192, 256, 384, 512],
    remotePatterns: [{ protocol: "https", hostname: "cdn.shopify.com" }],
  },
  async headers() {
    return [{ source: "/(.*)", headers: securityHeaders }];
  },
  async redirects() {
    // Old Hostinger URLs -> new routes (generated by scripts/clean-catalog.mjs)
    const legacy = (redirectsData as RedirectEntry[]).map(({ source, destination, permanent }) => ({
      source,
      destination,
      permanent,
    }));
    return [
      ...legacy,
      // French is the default locale and lives at the root: never expose /fr/...
      { source: "/fr", destination: "/", permanent: true },
      { source: "/fr/:path*", destination: "/:path*", permanent: true },
    ];
  },
};

export default nextConfig;
